//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inmobiliaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class casa
    {
        public int Idcasa { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> costo { get; set; }
        public string imagen { get; set; }
    }
}
